version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".formatter.exs",
 ".github/dependabot.yml",
 ".github/workflows/ci.yml",
 ".gitignore",
 ".iex.exs",
 ".cspell.json",
 ".tool-versions",
 "CHANGELOG.md",
 "config/**",
 "CONTRIBUTING.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock",
 "test/fixtures/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "guides/configuration.md",
 "guides/debugging.md",
 "guides/extensions.md",
 "README.md",
 "RELEASE.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nerves Hub Authors"
SPDX-License-Identifier = "CC-BY-4.0"
